pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		gradlePluginPortal()
		mavenLocal()
	}

	plugins {
		id 'net.fabricmc.filament' version "${filament_version}"
		id 'org.openjfx.javafxplugin' version "${javafx_plugin_version}"
	}
}

// This check is done here before any plugins that may require java 17 are able to load.
if (!JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_17)) {
	throw new UnsupportedOperationException("YT-RE requires Java 17 or higher.")
}

rootProject.name = "yt-re"

include ':tools:gitifier'
include ':tools:enigma-plugin'
include ':tools:stitch-plugin'
